@if "%LATEXWORKSHOP_DOCKER_SOURCE_DIR_HOST%"=="" set LATEXWORKSHOP_DOCKER_SOURCE_DIR_HOST=%cd%
@if "%LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER%"=="" set LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER=/latex-workshop/src
@if "%LATEXWORKSHOP_DOCKER_WORKDIR_CONTAINER%"=="" set LATEXWORKSHOP_DOCKER_WORKDIR_CONTAINER=%LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER%
@if "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%"=="" set LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER=/latex-workshop/out
@if "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST%"=="" set LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST=%cd%
@%LATEXWORKSHOP_DOCKER_PATH% run -i --rm --pull=never --network=none --cap-drop=ALL --security-opt=no-new-privileges -w "%LATEXWORKSHOP_DOCKER_WORKDIR_CONTAINER%" -v "%LATEXWORKSHOP_DOCKER_SOURCE_DIR_HOST%:%LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER%:ro" -v "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST%:%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%" -e "TEXMFVAR=%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%/.texlive-cache" -e "TEXMFCACHE=%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%/.texlive-cache" %LATEXWORKSHOP_DOCKER_LATEX% latexmk %*
