@if "%LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER%"=="" set LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER=/latex-workshop/src
@if "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%"=="" set LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER=/latex-workshop/out
@if "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST%"=="" set LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST=%cd%
@%LATEXWORKSHOP_DOCKER_PATH% run -i --rm --pull=never --network=none --cap-drop=ALL --security-opt=no-new-privileges -w %LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER% -v "%cd%:%LATEXWORKSHOP_DOCKER_SOURCE_DIR_CONTAINER%:ro" -v "%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_HOST%:%LATEXWORKSHOP_DOCKER_OUTPUT_DIR_CONTAINER%" %LATEXWORKSHOP_DOCKER_LATEX% latexmk %*
