#!/bin/sh
USER_ARGS=""
if command -v id >/dev/null 2>&1; then
    USER_ARGS="--user $(id -u):$(id -g)"
fi

exec "$LATEXWORKSHOP_DOCKER_PATH" run -i --rm --pull=never --network=none \
    --cap-drop=ALL --security-opt=no-new-privileges $USER_ARGS \
    -w "$(pwd)" -v "$(pwd):$(pwd):ro" "$LATEXWORKSHOP_DOCKER_LATEX" synctex "$@"
